feat: agent
data-platform-hq/terraform-azuredevops-project pull request #7
Opened 2023-07-06 12:59 UTC by Dmytrovel

2023-07-09 13:34 UTC, owlleg6 commented on variables.tf
> +    agent_name     = string
rename parameter to "name"

2023-07-09 13:38 UTC, owlleg6 commented on variables.tf
> +  default = {
provide default values, for example name is 'iacda', auto provision - true and auto update - true.

2023-07-09 13:39 UTC, owlleg6 commented on main.tf
> +  authorized  = var.pool_authorization.authorized
add white space before 'depends on' block

2023-07-09 13:40 UTC, owlleg6 commented on variables.tf
> +  description = "Objects to configure pool"
Update description to - 'Object with parameters to configure self-hosted agent pool'

2023-07-09 13:40 UTC, owlleg6 commented on variables.tf
> +  description = "Objects to configure pool authorization"
Update description to - 'Object with parameters to configure authorization of self-hosted agent pool'

2023-07-09 13:41 UTC, owlleg6 commented on outputs.tf
> +  value       = var.self_hosted_linux_agent_enable ? azuredevops_agent_pool.this[0].id : ""
you can use 'try' here, for example - try(azuredevops_agent_pool.this[0].id, null)

2023-07-09 13:41 UTC, owlleg6 commented on outputs.tf
> +  value       = var.self_hosted_linux_agent_enable ? azuredevops_agent_pool.this[0].name : ""
you can use 'try'

2023-07-09 13:42 UTC, owlleg6 requested changes
Review comments

2023-07-19 23:09 UTC, Dmytrovel commented on outputs.tf
> +  value       = try(azuredevops_agent_pool.this[0].id, null) # var.self_hosted_linux_agent_enable ? azuredevops_agent_pool.this[0].id : ""
+

2023-07-19 23:10 UTC, Dmytrovel commented on outputs.tf
> +  value       = try(azuredevops_agent_pool.this[0].id, null) # var.self_hosted_linux_agent_enable ? azuredevops_agent_pool.this[0].id : ""
done

2023-07-24 07:49 UTC, owlleg6 approved these changes

2023-07-24 07:50 UTC, merged